kind: Deployment
apiVersion: apps/v1
metadata:
  name: mariadb
  labels:
    app: mariadb
    part-of: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      part-of: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        part-of: nextcloud
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      serviceAccountName: nextcloud
      containers:
      - name: mariadb
        image: ghcr.io/linuxserver/mariadb:10.5.13
        ports:
        - name: mariadb
          containerPort: 3306
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_LOG_CONSOLE
          value: "true"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: nextcloud-mariadb
          mountPath: /config
        - name: nextcloud-secrets
          mountPath: "/mnt/vault"
          readOnly: true
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
      volumes:
      - name: nextcloud-mariadb
        persistentVolumeClaim:
          claimName: nextcloud-mariadb
      - name: nextcloud-secrets
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "nextcloud"
