kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud
  labels:
    app: nextcloud
    part-of: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      part-of: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
        part-of: nextcloud
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd   
      containers:
      - name: nextcloud
        image: ghcr.io/linuxserver/nextcloud:25.0.1-php8
        ports:
        - name: nextcloud
          containerPort: 443
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
        - name: TZ
          value: "Europe/Paris"
        volumeMounts:
        - name: nextcloud
          mountPath: /config
        - name: customscripts
          mountPath: /custom-cont-init.d
        - name: data
          mountPath: /data
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: customscripts
        persistentVolumeClaim:
          claimName: customscripts
